import { IMoexAsset } from './assetCatalogTypes';

export const MOEX_STOCKS: IMoexAsset[] = [
  { ticker: 'ABIO', name: 'Артген биотех', type: 'STOCK', aliases: ['ИСКЧ', 'ISKJ', 'Artgen'] },
  { ticker: 'AFKS', name: 'АФК Система', type: 'STOCK', aliases: ['Система', 'Sistema', 'AFK Sistema'] },
  { ticker: 'AFLT', name: 'Аэрофлот', type: 'STOCK', aliases: ['Aeroflot'] },
  { ticker: 'AKRN', name: 'Акрон', type: 'STOCK', aliases: ['Akron'] },
  { ticker: 'ALRS', name: 'Алроса', type: 'STOCK', aliases: ['АЛРОСА', 'Alrosa'] },
  { ticker: 'AQUA', name: 'ИНАРКТИКА', type: 'STOCK', aliases: ['Инарктика', 'Inarctica', 'Русская аквакультура'] },
  { ticker: 'ASTR', name: 'Группа Астра', type: 'STOCK', aliases: ['Астра', 'Astra'] },
  { ticker: 'BANE', name: 'Башнефть', type: 'STOCK', aliases: ['Bashneft'] },
  { ticker: 'BANEP', name: 'Башнефть Преф', type: 'STOCK', aliases: ['Башнефть ап', 'Башнефть привилегированные', 'Bashneft pref'] },
  { ticker: 'BELU', name: 'Новабев Групп (Белуга)', type: 'STOCK', aliases: ['Новабев', 'Белуга', 'Novabev', 'Beluga'] },
  { ticker: 'BSPB', name: 'Банк Санкт-Петербург', type: 'STOCK', aliases: ['Банк СПб', 'БСПБ', 'Bank Saint Petersburg'] },
  { ticker: 'CBOM', name: 'МКБ (Московский кредитный банк)', type: 'STOCK', aliases: ['МКБ', 'Credit Bank of Moscow'] },
  { ticker: 'CHMF', name: 'Северсталь', type: 'STOCK', aliases: ['Severstal'] },
  { ticker: 'CNRU', name: 'ЦИАН', type: 'STOCK', aliases: ['Циан', 'Cian', 'CIAN'] },
  { ticker: 'DELI', name: 'Делимобиль', type: 'STOCK', aliases: ['Delimobil'] },
  { ticker: 'DIAS', name: 'Диасофт', type: 'STOCK', aliases: ['Diasoft'] },
  { ticker: 'DOMRF', name: 'ДОМ.РФ', type: 'STOCK', aliases: ['Дом РФ', 'ДОМРФ', 'DOM RF'] },
  { ticker: 'ELFV', name: 'ЭЛ5-Энерго', type: 'STOCK', aliases: ['Энел Россия', 'Enel'] },
  { ticker: 'ENPG', name: 'ЭН+ ГРУП', type: 'STOCK', aliases: ['ЭН+ГРУП', 'Эн плюс', 'EN+', 'Enplus Group'] },
  { ticker: 'ETLN', name: 'Эталон', type: 'STOCK', aliases: ['Etalon'] },
  { ticker: 'EUTR', name: 'Евротранс', type: 'STOCK', aliases: ['ЕвроТранс', 'Eurotrans', 'Трасса'] },
  { ticker: 'FEES', name: 'Россети', type: 'STOCK', aliases: ['Rosseti', 'ФСК ЕЭС', 'ФСК Россети'] },
  { ticker: 'FESH', name: 'ДВМП (FESCO)', type: 'STOCK', aliases: ['ДВМП', 'Fesco'] },
  { ticker: 'FLOT', name: 'Совкомфлот', type: 'STOCK', aliases: ['Sovcomflot'] },
  { ticker: 'GAZP', name: 'Газпром', type: 'STOCK', aliases: ['Gazprom'] },
  { ticker: 'GEMC', name: 'Евромедцентр (ЮМГ)', type: 'STOCK', aliases: ['ЮМГ', 'Евромед', 'EMC', 'United Medical Group'] },
  { ticker: 'GMKN', name: 'Норильский никель', type: 'STOCK', aliases: ['Норникель', 'ГМК Норникель', 'Nornickel', 'Norilsk Nickel'] },
  { ticker: 'HEAD', name: 'Хэдхантер', type: 'STOCK', aliases: ['Хедхантер', 'ХэдХантер', 'HeadHunter', 'HH', 'HHRU'] },
  { ticker: 'HYDR', name: 'РусГидро', type: 'STOCK', aliases: ['Русгидро', 'RusHydro'] },
  { ticker: 'IRAO', name: 'ИнтерРАО', type: 'STOCK', aliases: ['Интер РАО', 'Inter RAO'] },
  { ticker: 'KMAZ', name: 'КАМАЗ', type: 'STOCK', aliases: ['Камаз', 'Kamaz'] },
  { ticker: 'LEAS', name: 'Европлан', type: 'STOCK', aliases: ['Europlan'] },
  { ticker: 'LENT', name: 'Лента', type: 'STOCK', aliases: ['Lenta'] },
  { ticker: 'LKOH', name: 'ЛУКОЙЛ', type: 'STOCK', aliases: ['Лукойл', 'Lukoil', 'Lukoyl'] },
  { ticker: 'LSNGP', name: 'Россети Ленэнерго Преф', type: 'STOCK', aliases: ['Ленэнерго преф', 'Ленэнерго ап', 'Lenenergo pref'] },
  { ticker: 'LSRG', name: 'Группа ЛСР', type: 'STOCK', aliases: ['ЛСР', 'LSR Group'] },
  { ticker: 'MAGN', name: 'ММК', type: 'STOCK', aliases: ['Магнитогорский металлургический комбинат', 'MMK'] },
  { ticker: 'MBNK', name: 'МТС Банк', type: 'STOCK', aliases: ['МТС банк', 'MTS Bank'] },
  { ticker: 'MDMG', name: 'Мать и дитя (MD Medical)', type: 'STOCK', aliases: ['Мать и дитя', 'MD Medical'] },
  { ticker: 'MGNT', name: 'Магнит', type: 'STOCK', aliases: ['Magnit'] },
  { ticker: 'MOEX', name: 'Мосбиржа', type: 'STOCK', aliases: ['Московская биржа', 'Moscow Exchange'] },
  { ticker: 'MRKC', name: 'Россети Центр', type: 'STOCK', aliases: ['Россети центр', 'МРСК Центра'] },
  { ticker: 'MRKP', name: 'Россети Центр и Приволжье', type: 'STOCK', aliases: ['Россети центр и прив', 'МРСК Центра и Приволжья'] },
  { ticker: 'MTLR', name: 'Мечел', type: 'STOCK', aliases: ['Mechel'] },
  { ticker: 'MTSS', name: 'МТС', type: 'STOCK', aliases: ['MTS', 'Мобильные телесистемы'] },
  { ticker: 'MVID', name: 'М.Видео', type: 'STOCK', aliases: ['М Видео', 'MVideo'] },
  { ticker: 'NLMK', name: 'НЛМК', type: 'STOCK', aliases: ['Новолипецкий металлургический комбинат'] },
  { ticker: 'NMTP', name: 'НМТП', type: 'STOCK', aliases: ['Новороссийский морской торговый порт'] },
  { ticker: 'NVTK', name: 'НОВАТЭК', type: 'STOCK', aliases: ['Новатэк', 'Novatek'] },
  { ticker: 'OZON', name: 'ОЗОН', type: 'STOCK', aliases: ['Озон', 'Ozon'] },
  { ticker: 'PHOR', name: 'ФосАгро', type: 'STOCK', aliases: ['Фосагро', 'PhosAgro'] },
  { ticker: 'PIKK', name: 'ПИК', type: 'STOCK', aliases: ['PIK Group'] },
  { ticker: 'PLZL', name: 'Полюс Золото', type: 'STOCK', aliases: ['Полюс', 'Polyus'] },
  { ticker: 'POSI', name: 'Позитив (Positive Technologies)', type: 'STOCK', aliases: ['Позитив', 'Positive Technologies'] },
  { ticker: 'RAGR', name: 'Русагро', type: 'STOCK', aliases: ['РусАгро', 'Rusagro', 'AGRO'] },
  { ticker: 'RASP', name: 'Распадская', type: 'STOCK', aliases: ['Raspadskaya'] },
  { ticker: 'RENI', name: 'Ренессанс Страхование', type: 'STOCK', aliases: ['Ренессанс', 'Renaissance Insurance'] },
  { ticker: 'RNFT', name: 'Русснефть', type: 'STOCK', aliases: ['РуссНефть', 'Russneft'] },
  { ticker: 'ROSN', name: 'Роснефть', type: 'STOCK', aliases: ['Rosneft'] },
  { ticker: 'RTKM', name: 'Ростелеком', type: 'STOCK', aliases: ['Rostelecom'] },
  { ticker: 'RUAL', name: 'Русал', type: 'STOCK', aliases: ['РУСАЛ', 'Rusal'] },
  { ticker: 'SBER', name: 'Сбербанк', type: 'STOCK', aliases: ['Сбер', 'Sber', 'Sberbank'] },
  { ticker: 'SBERP', name: 'Сбербанк Преф', type: 'STOCK', aliases: ['Сбер преф', 'Сбербанк ап', 'Sber pref'] },
  { ticker: 'SELG', name: 'Селигдар', type: 'STOCK', aliases: ['Seligdar'] },
  { ticker: 'SFIN', name: 'ЭсЭфАй', type: 'STOCK', aliases: ['Эсэфай', 'SFI', 'Сафмар'] },
  { ticker: 'SGZH', name: 'Сегежа', type: 'STOCK', aliases: ['Segezha'] },
  { ticker: 'SIBN', name: 'ГазпромНефть', type: 'STOCK', aliases: ['Газпром нефть', 'Gazprom Neft'] },
  { ticker: 'SMLT', name: 'Самолет', type: 'STOCK', aliases: ['Самолёт', 'Samolet'] },
  { ticker: 'SNGS', name: 'Сургутнефтегаз', type: 'STOCK', aliases: ['Сургут', 'Surgutneftegas'] },
  { ticker: 'SNGSP', name: 'Сургутнефтегаз Преф', type: 'STOCK', aliases: ['Сургут преф', 'Сургутнефтегаз ап', 'Surgutneftegas pref'] },
  { ticker: 'SOFL', name: 'Софтлайн', type: 'STOCK', aliases: ['Softline', 'SFTL'] },
  { ticker: 'SPBE', name: 'Биржа Санкт-Петербург', type: 'STOCK', aliases: ['СПБ Биржа', 'Спб биржа', 'SPB Exchange'] },
  { ticker: 'SVCB', name: 'Совкомбанк', type: 'STOCK', aliases: ['Sovcombank'] },
  { ticker: 'T', name: 'Т-Технологии', type: 'STOCK', aliases: ['Т', 'Т-Банк', 'Тинькофф', 'Tinkoff', 'TCSG', 'T-Bank'] },
  { ticker: 'TATN', name: 'Татнефть', type: 'STOCK', aliases: ['Tatneft'] },
  { ticker: 'TATNP', name: 'Татнефть Преф', type: 'STOCK', aliases: ['Татнефть ап', 'Tatneft pref'] },
  { ticker: 'TRNFP', name: 'Транснефть Преф', type: 'STOCK', aliases: ['Транснефть', 'Транснефть ап', 'Transneft pref'] },
  { ticker: 'UGLD', name: 'ЮГК (Южуралзолото)', type: 'STOCK', aliases: ['ЮГК', 'Южуралзолото', 'UGC'] },
  { ticker: 'UPRO', name: 'Юнипро', type: 'STOCK', aliases: ['Unipro'] },
  { ticker: 'UWGN', name: 'ОВК (Объединенная вагонная компания)', type: 'STOCK', aliases: ['ОВК', 'United Wagon Company'] },
  { ticker: 'VKCO', name: 'ВКонтакте (VK)', type: 'STOCK', aliases: ['Вконтакте', 'ВК', 'VK', 'MAIL'] },
  { ticker: 'VSEH', name: 'ВсеИнструменты.ру', type: 'STOCK', aliases: ['ВсеИнструменты', 'Vseinstrumenty'] },
  { ticker: 'VTBR', name: 'ВТБ', type: 'STOCK', aliases: ['VTB'] },
  { ticker: 'WUSH', name: 'ВУШ (Whoosh)', type: 'STOCK', aliases: ['Вуш', 'Whoosh'] },
  { ticker: 'X5', name: 'X5 Group (Пятёрочка)', type: 'STOCK', aliases: ['Х5', 'Пятерочка', 'Пятёрочка', 'Перекресток', 'FIVE'] },
  { ticker: 'YDEX', name: 'Яндекс', type: 'STOCK', aliases: ['Yandex', 'YNDX'] },
  { ticker: 'ZAYM', name: 'Займер', type: 'STOCK', aliases: ['Zaimer'] },
];
